apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: codefresh
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-9100eee6-96aa-41f5-9865-c4c385a3861b
      eventName: github-9100eee6-96aa-41f5-9865-c4c385a3861b
      eventSourceName: codefresh
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: cd
        conditions: github-9100eee6-96aa-41f5-9865-c4c385a3861b
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: codefresh-cd-
              spec:
                workflowTemplateRef:
                  name: hello-world-pipeline
          parameters: []
