apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-mastermind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - name: word-mastermind
        image: mashabrauer/word-mastermind:1.0
        ports:
        - containerPort: 80
        env:
        - name: LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: PORT
          value: "80"


---


apiVersion: v1
kind: Service
metadata:
  name: word-mastermind-service
spec:
  selector:
    app: words
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort